### ISSUE TITLE
Crash on gradle build

### ISSUE THREAD

**Issue by Ivaskuu** [nanowang/flutter_animated#13]
Hi, I've just installed the plugin, and added an AnimatedGif to test, and it gave me this error on executing flutter run :

Running 'gradle assembleDebug'...
Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configur
ation failure takes precedence.
java.lang.IllegalStateException: buildToolsVersion is not specified.
        at com.google.common.base.Preconditions.checkState(Preconditions.java:17
3)
        at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.jav
a:645)
        at com.android.build.gradle.BasePlugin$10.call(BasePlugin.java:608)
        at com.android.build.gradle.BasePlugin$10.call(BasePlugin.java:605)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java
:156)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java
:120)
        at com.android.build.gradle.BasePlugin.lambda$createTasks$1(BasePlugin.j
ava:603)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.d
ispatch(BroadcastDispatch.java:93)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.d
ispatch(BroadcastDispatch.java:82)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(Abstract
BroadcastDispatch.java:44)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatc
h.java:79)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatc
h.java:30)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocati
onHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy15.afterEvaluate(Unknown Source)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfte
rEvaluate(LifecycleProjectEvaluator.java:67)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(L
ifecycleProjectEvaluator.java:61)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProjec
t.java:573)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProjec
t.java:125)
        at org.gradle.api.internal.project.DefaultProjectAccessListener.evaluate
ProjectAndDiscoverTasks(DefaultProjectAccessListener.java:32)
        at org.gradle.api.internal.project.DefaultProjectAccessListener.beforeRe
solvingProjectDependency(DefaultProjectAccessListener.java:28)
        at org.gradle.api.internal.artifacts.dependencies.DefaultProjectDependen
cy.beforeResolved(DefaultProjectDependency.java:133)
        at org.gradle.api.internal.artifacts.ivyservice.moduleconverter.dependen
cies.ProjectIvyDependencyDescriptorFactory.createDependencyDescriptor(ProjectIvy
DependencyDescriptorFactory.java:40)
        at org.gradle.api.internal.artifacts.ivyservice.moduleconverter.dependen
cies.DefaultDependencyDescriptorFactory.createDependencyDescriptor(DefaultDepend
encyDescriptorFactory.java:36)
        at org.gradle.api.internal.artifacts.ivyservice.moduleconverter.dependen
cies.DefaultDependenciesToModuleDescriptorConverter.addDependencies(DefaultDepen
denciesToModuleDescriptorConverter.java:43)
        at org.gradle.api.internal.artifacts.ivyservice.moduleconverter.dependen
cies.DefaultDependenciesToModuleDescriptorConverter.addDependencyDescriptors(Def
aultDependenciesToModuleDescriptorConverter.java:36)
        at org.gradle.api.internal.artifacts.ivyservice.moduleconverter.DefaultC
onfigurationComponentMetaDataBuilder.addDependencies(DefaultConfigurationCompone
ntMetaDataBuilder.java:51)
        at org.gradle.api.internal.artifacts.ivyservice.moduleconverter.DefaultC
onfigurationComponentMetaDataBuilder.addConfigurations(DefaultConfigurationCompo
nentMetaDataBuilder.java:39)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration
.toRootComponentMetaData(DefaultConfiguration.java:584)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArt
ifactDependencyResolver$DefaultResolveContextToComponentResolver.resolve(Default
ArtifactDependencyResolver.java:135)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.Depe
ndencyGraphBuilder.resolve(DependencyGraphBuilder.java:87)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArt
ifactDependencyResolver.resolve(DefaultArtifactDependencyResolver.java:82)
        at org.gradle.api.internal.artifacts.ivyservice.CacheLockingArtifactDepe
ndencyResolver$1.run(CacheLockingArtifactDependencyResolver.java:41)
        at org.gradle.internal.Factories$1.create(Factories.java:25)
        at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAcc
ess.java:179)
        at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAcc
ess.java:162)
        at org.gradle.cache.internal.DefaultPersistentDirectoryStore.useCache(De
faultPersistentDirectoryStore.java:129)
        at org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.
useCache(DefaultCacheFactory.java:191)
        at org.gradle.api.internal.artifacts.ivyservice.DefaultCacheLockingManag
er.useCache(DefaultCacheLockingManager.java:56)
        at org.gradle.api.internal.artifacts.ivyservice.CacheLockingArtifactDepe
ndencyResolver.resolve(CacheLockingArtifactDependencyResolver.java:39)
        at org.gradle.api.internal.artifacts.ivyservice.DefaultConfigurationReso
lver.resolve(DefaultConfigurationResolver.java:97)
        at org.gradle.api.internal.artifacts.ivyservice.SelfResolvingDependencyC
onfigurationResolver.resolve(SelfResolvingDependencyConfigurationResolver.java:4
0)
        at org.gradle.api.internal.artifacts.ivyservice.ShortCircuitEmptyConfigu
rationResolver.resolve(ShortCircuitEmptyConfigurationResolver.java:62)
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurati
onResolver.resolve(ErrorHandlingConfigurationResolver.java:43)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration
.resolveGraphIfRequired(DefaultConfiguration.java:399)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration
.resolveNow(DefaultConfiguration.java:374)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration
.getResolvedConfiguration(DefaultConfiguration.java:367)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration
_Decorated.getResolvedConfiguration(Unknown Source)
        at com.android.build.gradle.internal.DependencyManager.collectArtifacts(
DependencyManager.java:497)
        at com.android.build.gradle.internal.DependencyManager.gatherDependencie
s(DependencyManager.java:375)
        at com.android.build.gradle.internal.DependencyManager.resolveDependency
ForConfig(DependencyManager.java:278)
        at com.android.build.gradle.internal.DependencyManager.resolveDependenci
es(DependencyManager.java:155)
        at com.android.build.gradle.internal.TaskManager.resolveDependencies(Tas
kManager.java:364)
        at com.android.build.gradle.internal.VariantManager$9.call(VariantManage
r.java:636)
        at com.android.build.gradle.internal.VariantManager$9.call(VariantManage
r.java:633)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java
:156)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java
:120)
        at com.android.build.gradle.internal.profile.SpanRecorders.record(SpanRe
corders.java:44)
        at com.android.build.gradle.internal.VariantManager.createVariantData(Va
riantManager.java:629)
        at com.android.build.gradle.internal.VariantManager.createVariantDataFor
ProductFlavors(VariantManager.java:823)
        at com.android.build.gradle.internal.VariantManager.populateVariantDataL
ist(VariantManager.java:494)
        at com.android.build.gradle.internal.VariantManager$1.call(VariantManage
r.java:269)
        at com.android.build.gradle.internal.VariantManager$1.call(VariantManage
r.java:266)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java
:156)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java
:120)
        at com.android.build.gradle.internal.VariantManager.createAndroidTasks(V
ariantManager.java:265)
        at com.android.build.gradle.BasePlugin$11.call(BasePlugin.java:688)
        at com.android.build.gradle.BasePlugin$11.call(BasePlugin.java:685)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java
:156)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java
:120)
        at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.jav
a:683)
        at com.android.build.gradle.BasePlugin$10.call(BasePlugin.java:608)
        at com.android.build.gradle.BasePlugin$10.call(BasePlugin.java:605)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java
:156)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java
:120)
        at com.android.build.gradle.BasePlugin.lambda$createTasks$1(BasePlugin.j
ava:603)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.d
ispatch(BroadcastDispatch.java:93)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.d
ispatch(BroadcastDispatch.java:82)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(Abstract
BroadcastDispatch.java:44)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatc
h.java:79)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatc
h.java:30)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocati
onHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy15.afterEvaluate(Unknown Source)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfte
rEvaluate(LifecycleProjectEvaluator.java:67)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(L
ifecycleProjectEvaluator.java:61)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProjec
t.java:573)
        at org.gradle.api.internal.project.DefaultProject.evaluationDependsOn(De
faultProject.java:645)
        at org.gradle.api.internal.project.DefaultProject.evaluationDependsOn(De
faultProject.java:637)
        at org.gradle.api.Project$evaluationDependsOn.call(Unknown Source)
        at build_i2ofk8sekstcnancs9finzvz$_run_closure2.doCall(C:\Users\Ileana\D
ocuments\chat_diary\android\build.gradle:24)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:
93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(C
losureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
        at groovy.lang.Closure.call(Closure.java:414)
        at groovy.lang.Closure.call(Closure.java:430)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedActi
on.java:70)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)

        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
        at org.gradle.api.internal.project.DefaultProject.configure(DefaultProje
ct.java:921)
        at org.gradle.api.internal.project.DefaultProject.configure(DefaultProje
ct.java:926)
        at org.gradle.api.internal.project.DefaultProject.subprojects(DefaultPro
ject.java:909)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:
93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.inv
okeMethod(BeanDynamicObject.java:382)
        at org.gradle.internal.metaobject.BeanDynamicObject.invokeMethod(BeanDyn
amicObject.java:170)
        at org.gradle.internal.metaobject.CompositeDynamicObject.invokeMethod(Co
mpositeDynamicObject.java:96)
        at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamic
Object.invokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
        at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(Abs
tractDynamicObject.java:163)
        at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:
83)
        at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:
93)
        at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:941)

        at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:
1264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(Po
goMetaClassSite.java:69)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(Abs
tractCallSite.java:166)
        at build_i2ofk8sekstcnancs9finzvz.run(C:\Users\Ileana\Documents\chat_dia
ry\android\build.gradle:22)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptR
unnerImpl.run(DefaultScriptRunnerFactory.java:90)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$
2.run(DefaultScriptPluginFactory.java:176)
        at org.gradle.configuration.ProjectScriptTarget.addConfiguration(Project
ScriptTarget.java:77)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.
apply(DefaultScriptPluginFactory.java:181)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildSc
riptProcessor.java:38)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildSc
riptProcessor.java:25)
        at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.eva
luate(ConfigureActionsProjectEvaluator.java:34)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(L
ifecycleProjectEvaluator.java:55)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProjec
t.java:573)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProjec
t.java:125)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(Task
PathProjectEvaluator.java:42)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuil
dConfigurer.java:38)
        at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLa
uncher.java:162)
        at org.gradle.internal.Factories$1.create(Factories.java:25)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul
tBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul
tBuildOperationExecutor.java:53)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(Default
GradleLauncher.java:159)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGra
dleLauncher.java:36)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradl
eLauncher.java:118)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradl
eLauncher.java:112)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul
tBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul
tBuildOperationExecutor.java:63)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradle
Launcher.java:112)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLaun
cher.java:98)
        at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildControl
ler.java:66)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(Exe
cuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildA
ctionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
ssBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
ssBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.ex
ecute(ContinuousBuildActionExecuter.java:75)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.ex
ecute(ContinuousBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter
.execute(ServicesSetupBuildActionExecuter.java:44)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter
.execute(ServicesSetupBuildActionExecuter.java:29)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBu
ild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(Build
CommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(
WatchForDisconnection.java:47)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute
(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.
execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(Forw
ardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(Forw
ardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(For
wardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogA
ndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClien
t.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(Build
CommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBu
ild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(Build
CommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.
run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(Daemon
StateCoordinator.java:293)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.
onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableE
xecutorImpl.java:40)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Ileana\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\fl
utter_animated-0.0.4\android\build.gradle' line: 21

* What went wrong:
A problem occurred evaluating project ':flutter_animated'.
> Plugin with id 'kotlin-android' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.
Gradle build failed: 1

**Comment by namiwang** [comment]
@Ivaskuu Thanks for reporting, seems like an issue out of the plugin itself, will look into it.
